{{- if .Values.clusterGroup.isHubCluster }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: job-wait-for-vault
  # By placing the job in the vault namespace
  namespace: vault
spec:
  template:
    spec:
      containers:
      - image: FIXME
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=condition=Ready=true pods -n vault vault-0 --timeout=900s
        name: wait-for-healthy-vault
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: vault
      serviceAccountName: vault
      terminationGracePeriodSeconds: 60
{{ end }}
